#!/usr/bin/python
import string
import random
import boto.ec2
kp_name = ''.join(random.choice(string.letters) for i in xrange(16))
ec2 = boto.ec2.connect_to_region('{"Ref" : "AWS::Region" }')
keypair = ec2.create_key_pair(kp_name)
keypair.save('/home/ec2-user/.ssh/')
with file('/home/ec2-user/bees_keypair.txt', 'w') as f:
     f.write(kp_name)
print 'Created keypair: %s' % kp_name