#!/bin/bash
yum update -y aws-cfn-bootstrap
/opt/aws/bin/cfn-init -v -s { "Ref": "AWS::StackName" } \
    -r BeeController --access-key { "Ref": "CfnKeys" } \
    --secret-key { "Fn::GetAtt": ["CfnKeys", "SecretAccessKey"] } \
    --region {  "Ref": "AWS::Region" } \
/opt/aws/bin/cfn-signal -e $? '{ "Ref" : "ControllerHandle" }'