#!/usr/bin/python
import string
import random
import boto.ec2
import os
import sys
if not os.path.exists('/home/ec2-user/bees_keypair.txt'):
     print >> sys.stderr, 'bees_keypair.txt does not exist'
     sys.exit(-1)
with file('/home/ec2-user/bees_keypair.txt', 'r') as f:
     kp_name = f.read().strip()
ec2 = boto.ec2.connect_to_region('{"Ref" : "AWS::Region" }')
ec2.delete_key_pair(kp_name)
os.remove('/home/ec2-user/bees_keypair.txt')
os.remove('/home/ec2-user/.ssh/%s.pem' % kp_name)
print 'Deleted keypair: %s' % kp_name