#!/usr/bin/python
import boto.ec2.elb
import sys
import time
elb = boto.ec2.elb.ELBConnection()
for i in range(120):
   if i > 0:
      time.sleep(5)
   health=elb.describe_instance_health('{ "Ref": "ElasticLoadBalancer" }')
   healthy_instances = [i for i in health if i.state == 'InService']
   if len(healthy_instances) == { "Ref": "AppInstanceCountDesired" }:
      break
else:
   print >> sys.stderr, 'Gave up waiting for { "Ref": "AppInstanceCountDesired" } instances.'
   sys.exit(1)